#!/bin/sh

# Install ansible aur library
git clone https://github.com/kewlfft/ansible-aur.git ~/.ansible/plugins/modules/aur

# Install ansible
sudo pacman --noconfirm -S ansible

# Execute base install
ansible-playbook ~/deployment/playbook_base-install.yml

HOSTNAME=$(hostname)

if [ "$HOSTNAME" = "Cellaris" ]
then
	ansible-playbook ~/deployment/playbook_home-install.yml
fi
