---
- hosts: localhost
  become: true
  become_user: julius

  tasks:
    - name: Make sure we have a 'wheel' group
      group:
        name: wheel
        state: present

    - user:
        name: julius
        state: present

    - name: Install base packages
      pacman:
        name:
          - git
          - ibus
          - xorg-server
          - xorg-xinit
          - xorg-xinput
          - xorg-xrandr
          - base-devel
          - tmux
          - byobu
          - ripgrep
          - wget
          - adobe-source-han-sans-jp-fonts
          - ttf-fira-code
          - sxhkd
          - rofi
          - bspwm
          - tint2
          - i3-gaps
        state: present
      become: true
      become_user: root

    - name: Install ease of use packages
      pacman:
        name:
          - atool
          - astyle
          - gopass
          - pandoc
          - elinks
          - nextcloud-client
          - noto-fonts-emoji
          - highlight
          - mediainfo
          - xdotool
          - anki
          - bat
          - dash
          - playerctl
          - wmctrl
          - entr
          - translate-shell
          - emacs
          - beep
          - fd
          - sshfs
          - shellcheck
          - rust
          - rust-racer
          - clang
          - ruby
          - maim
          - trash-cli
          - pwgen
          - etckeeper
          - fzf
          - neomutt
          - xfce4-notifyd
          - light
          - zsh
          - flatpak
          - fish
          - picom
          - docker
          - feh
          - gnome-system-monitor
          - kitty
          - htop
          - lsd
          - dolphin
          - openssh
          - p7zip
          - zip
          - unzip
          - unrar
          - physlock
          - pulseaudio
          - pavucontrol-qt
          - pulsemixer
          - python-pillow
          - python-pip
          - ranger
          - ueberzug
          - ttf-dejavu
          - ttf-liberation
          - xclip
          - xsel
          - yarn
          - zathura
          - zathura-pdf-mupdf
          - ansible
          - cronie
          - hub
          - make
          - unclutter
          - neofetch
      become: true
      become_user: root

    - name: Install zplug
      become: true
      become_user: julius
      shell: curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh
      ignore_errors: yes

    - name: Install yay
      aur:
        name:
          - yay

    - name: Install aur-packages
      aur:
        name:
          - xkeysnail
          - neovim-git
          - lnav
          - direnv
          - tealdeer
          - starship
          - zoxide
          - downgrade
          - ffsend-bin
          - nerd-fonts-jetbrains-mono
          - dragon-drag-and-drop
          - radeontop
          - yadm-git
          - nyrna
          - touchpad-toggle
          - brave-nightly-bin

    - name: Install pip-packages
      pip:
        name:
          - neovim
        extra_args: --user

    - name: Clone dotfiles
      command: yadm clone https://github.com/juligreen/Configfiles.git
      become: yes
      become_user: julius
      ignore_errors: yes

    - name: Enable multilib repos
      replace:
        path: /etc/pacman.conf
        regexp: '#\[multilib\]\n#.*'
        replace: "[multilib]\nInclude = /etc/pacman.d/mirrorlist"
      become: yes
      become_user: root

    - name: Enable colors
      replace:
        path: /etc/pacman.conf
        regexp: '#Color'
        replace: "Color"
      become: yes
      become_user: root
