---
- hosts: localhost
  become: true
  become_user: julius

  tasks:
    - name: pacman packages
      pacman:
        update_cache: yes
        name:
          - steam
          - discord
          - lutris
          - wine-staging
          - lib32-libpulse
          - vulkan-icd-loader
          - lib32-vulkan-icd-loader
          - picard
      become: yes
      become_user: root

    - name: aur packages
      aur:
        name:
          - steam-fonts
